### ISSUE TITLE
Is it correct the heat kernel definition?

### ISSUE THREAD

**Issue by FMagnani** [JAVI897/Laplacian-Eigenmaps#1]
https://github.com/JAVI897/Laplacian-Eigenmaps/blob/9e596e0b2ea847f7410364876538d496d8a51689/LE.py#L97

The Heat Kernel should use the squared distance in the numerator, doesn't it?
I am referencing the paper "Laplacian Eigenmaps for Dimensionality Reduction and Data Representation" by Belkin and Niyogi, page 1376.
In practice I think that the code should be corrected as `return np.exp(- dist*dist/self.sigma)`

**Comment by JAVI897** [comment]
Yes, you're right. I'll try to fix it as soon as I can. Thanks!
